### ISSUE TITLE
Twitter Button

### ISSUE THREAD

**Issue by Polymorphin** [erjjones/Feedback#10]
Hi Eric, i modified the forked blog for my personal use. I fixxed the most things until i liked it. Can oyu tell me how to remove your @erjjones when i hit the twitter button at an article?

http://polymorphin.github.io/blog/Polymorphin's-Blog-geht-Online/

**Comment by erjjones** [comment]
Thanks for the question. You will want to edit the twitter `<a href="https://twitter.com/share" class="twitter-share-button" data-via="erjjones">Tweet</a>` and change the `data-via` value to your twitter username.

If you are still using my original blog layout the file is located in the includes folder and it is titled "post_header". The twitter link is on line 25.

**Comment by Polymorphin** [comment]
Helped me alot.

**Comment by erjjones** [comment]
I noticed your site footer has some issues staying attached to the bottom of the page. Try this https://github.com/erjjones/footer-at-bottom
