### ISSUE TITLE
The number of comments in Disqus for each post is not accurately reflected on the home page

### ISSUE THREAD

**Issue by srmor** [erjjones/Feedback#3]
On the homepage the number of comments for each post remains at zero even though there are comments.

**Comment by erjjones** [comment]
Yeah.  I was trying to figure out a fix.  Still not sure.

**Comment by srmor** [comment]
If you figure that out I would love to know how you did it :)

**Comment by erjjones** [comment]
Will do.

**Comment by erjjones** [comment]
Change set https://github.com/erjjones/erjjones.github.com/commit/ebe0288e05eff24910142c93b33922041682ec55 fixed this issue and I have gist that will show some sample code https://gist.github.com/2026102
