### ISSUE TITLE
files in _post directoy are marked as Markdown but seem to be processed HTML

### ISSUE THREAD

**Issue by tooh** [erjjones/Feedback#6]
Hi Eric,

I came across your project and I am trying to set it up on http://tooh.github.io.

I have some trouble making things work especially with the comments system.
It seems in your example there is code that I cannot find in a template.

I am looking at the markdown posts as an example but it seems as if they are not markdown format so it is hard for me to search for the bits to change. Can you offer some existence.

Peter

**Comment by tooh** [comment]
OK, just saw the other comment about the Markdown /HTML.

Remains the question about the Comment ,Twitter and Google Plus bits in your posts. 

What should be the correct post template to incorporate those features

**Comment by erjjones** [comment]
tooh thanks for the question.  I would suggest putting your widget code in the post template/layout and use the property tags to supply the values you need to your widgets.  {{ object.property}}  This would allow you to keep your posts to just markdown.
