### ISSUE TITLE
Question about Jekyll

### ISSUE THREAD

**Issue by srussell123** [erjjones/Feedback#7]
Eric,
Thanks for your detailed blog post about setting up your site/blog with Jekyll.  I am in the process of following the steps and have installed ruby, jekyll and have it running locally in my username.github.io file.  

My question is, I noticed immediately that Jekyll creates a _site folder that copies all of the contents of my master username.github.io folder.  Your github page, however, does not have that.  Am I on the right track here or is something fishy about it?

**Comment by erjjones** [comment]
You are absolutely on the right path. Sorry I didn't mention it. Jekyll is technically a static website generator. When you run the Jekyll Server it will build out your entire site and put it in the _site folder. When GitHub servers up your site they actually server it from the _site folder.

**Comment by srussell123** [comment]
Thanks, I've read up now on the way Jekyll manages the site. My knee-jerk reaction to having a different root folder from you was that I had messed up.  Thank you again for your explanation.
