### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by barun-saha** [erjjones/Feedback#8]
Hello,

Nice to read your post! Am, too, planning to explore jekyll.
Just curious to know -- is this feedback option similar to leaving a comment in a blog post? And is this open to all users or only to the GitHub users?

Thanks.

**Comment by erjjones** [comment]
A comment on a post can't be tracked and assigned to others to deliberately handle. I use the Feedback repo for tracking specific issues and questions.  This feature is available on all GitHub repos and I just choose to use this repo solely for feedback and not code.
